### PR TITLE
add space to define docket_number

### PR DESCRIPTION
**Pull request by miabonardi**

### CODE REVIEW

**Review by nonprofittechy — COMMENTED** [review]
Can you explain this change more? I'm a bit worried this will break existing logic (anything that checks `if docket_number` will get a different result now)

**Comment by miabonardi** [comment]
Here's a short recording of me explaining: https://suffolk.zoom.us/rec/share/T7q6l-yC9gOb_cxrycDa9uGhlXqAPaZ9wsQl5005FDXyqSA4h1zP5DxxlcQTyUOr.MM0RRTgOmO6-JZl8?startTime=1704814179000

I think the validation error of plural `docket_numbers` not being defined may be coming from here: https://github.com/SuffolkLITLab/docassemble-ALMassachusetts/blob/4218d2edf8f70a9b3cf87b5d454087ffb9be6e35/docassemble/ALMassachusetts/data/questions/al_massachusetts.yml#L269-L285

**Comment by samglover** [comment]
It looks like this is [already being used](https://github.com/nonprofittechy/docassemble-FinancialStatementShortForm/blob/5918529333f533442cd038e756737484f7bd026d/docassemble/FinancialStatementShortForm/data/questions/Financial_statement_short_form.yml#L337) in the nonprofittechy/docassemble-FinancialStatementShortForm repository.

I didn't find anything in the [SuffolkLITLab](https://github.com/search?q=org%3ASuffolkLITLab+%22if+docket_number%22&type=code) or [nonprofittechy](https://github.com/search?q=user%3Anonprofittechy+%22if+docket_number%22&type=code) repos that would be obviously affected by this. But since it does flip the expected result of `if docket_number` from false to true, would it be worth either (1) additional documentation so that future interview builders know what to expect, or (2) setting `docket_number` to something like "none provided" instead of a space, which might be harder to troubleshoot?

**Comment by nonprofittechy** [comment]
I don't think we should make this change.

**Comment by samglover** [comment]
I'll close this PR, then.

**Pull request closed without merging**
