### PR TITLE
BBO Number with Validation

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Adds a BBO number question with validation. Was originally going to keep this unvalidated in AssemblyLine, but the Appeals Court asked for https://github.com/SuffolkLITLab/docassemble-AppealsCivilDocketingStatement/issues/14, so I thought we didn't want to force verification on everyone for the bootcamp.

The validation is just to ensure that the number is 6 digits, possibly with leading 0's. Also points out what character isn't the digit.

Related to https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/23.

### CODE REVIEW

**Comment by nonprofittechy** [comment]
I'm not positive we want validation here.

**Comment by BryceStevenWilley** [comment]
I thought so too, but it is feedback directly from Paul https://github.com/SuffolkLITLab/docassemble-AppealsCivilDocketingStatement/issues/14.  It is level 4, so we can probably sit on it for a while.

**Comment by nonprofittechy** [comment]
In that case: let's attach validation to the question for the Appeals Court forms, but not make it the default for all forms.

**Comment by nonprofittechy** [comment]
We should eventually have an ql_appeals_court.yml file

**Pull request merged**
